# Generated by Django 5.0 on 2023-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('rec1', models.CharField(max_length=30)),
                ('rec2', models.CharField(max_length=30)),
                ('rec3', models.CharField(max_length=30)),
                ('rec4', models.CharField(max_length=30)),
                ('rec5', models.CharField(max_length=30)),
                ('rec6', models.CharField(max_length=30)),
                ('rec7', models.CharField(max_length=30)),
                ('rec8', models.CharField(max_length=30)),
                ('rec9', models.CharField(max_length=30)),
                ('rec10', models.CharField(max_length=30)),
            ],
        ),
    ]
